#!/bin/bash

git config --global user.email "mr6r1n@gmail.com"
git config --global user.name "MGrin"
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status

git config --global credential.helper osxkeychain
